# Generated by Django 4.0.6 on 2022-08-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_order_total_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
