# Generated by Django 4.0.6 on 2022-08-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_number',
        ),
    ]
